function asyncFunction1() {
  return new Promise(function (resolve) {
    setTimeout(function() {
      resolve(111)
    }, 300)
  })
}

async function async1() {
  const result = await asyncFunction1()
  // await 키워드로 다른 promise를 반환하는 함수의 실행 결과값을 변수에 담을 수 있습니다.
  console.log(result) // 111
}

async function async2() {
  let result
  try {
    result = await asyncFunction1()
  } catch (error) { // await에서 발생한 에러는 모두 아래 catch 블록에 걸립니다.
    console.log(error)
  }
  if (result === 'AAA') { // if문 분기도 일반 동기함수처럼 작성 가능합니다.
    doSomething()
  }
  return result
}
